In [1]:
import numpy as np
print("DAY 1 : Sonar Sweep")
inp = np.genfromtxt("inputs_2021/1.txt")
score = 0
for i in range(1, len(inp)):
    if inp[i] > inp[i-1]:
        score+=1
print("Part 1:",score)
score2 = 0
for i in range(4, len(inp)):
    if np.sum(inp[i-2:i+1]) > np.sum(inp[i-3:i]):
        score2+=1
print("Part 2:",score2)

DAY 1 : Sonar Sweep
Part 1: 1448
Part 2: 1471


In [2]:
print("DAY 2 : Dive!")
inp_2 = []
for line in open("inputs_2021/2.txt"):
    inp_2.append((line.split(" ")[0], int(line.split(" ")[1][0])))
    
horiz = 0
depth = 0

for move in inp_2:
    if move[0]=='forward':
        horiz+=int(move[1])
    elif move[0]=='down':
        depth+=int(move[1])
    else:
        depth-=int(move[1])
print("Part 1:", horiz*depth)

horiz = 0
depth = 0
aim = 0

for move in inp_2:
    if move[0]=='forward':
        horiz+=int(move[1])
        depth+=move[1]*aim
    elif move[0]=='down':
        aim+=int(move[1])
    else:
        aim-=int(move[1])
print("Part 2:", horiz*depth)

DAY 2 : Dive!
Part 1: 2039912
Part 2: 1942068080


In [3]:
print("DAY 3 : Binary Diagnostic")
bit_counter = np.zeros(12)
input_3 = []
for line in open("inputs_2021/3.txt"):
    input_3.append(np.array([1 if bit =="1" else 0 for bit in line[:12]]))
    for i,bit in enumerate(line[:-1]):
        if bit=="1":
            bit_counter[i]+=1
        else:
            bit_counter[i]-=1

gamma = 0
epsilon = 0
for i in range(len(bit_counter)):
    if bit_counter[-i-1] > 0:
        gamma+=2**i
    else:
        epsilon+=2**i
print("Part 1:", gamma*epsilon)
oxygen = np.array(input_3)
co2 = np.array(input_3)
rank = 0
while len(oxygen) > 1:
    criteria_o = 0
    if np.sum(np.array(oxygen[:,rank], dtype=int)) >= len(oxygen)/2:
        criteria_o = 1
    oxygen = np.array([nb for nb in oxygen if nb[rank]==criteria_o])
    rank+=1

rank=0
while len(co2) > 1:
    criteria_c = 0
    if np.sum(np.array(co2[:,rank], dtype=int)) < len(co2)/2:
        criteria_c = 1
    co2 = np.array([nb for nb in co2 if nb[rank]==criteria_c])
    rank+=1

oxygen_dec = np.sum([2**(11-i) if ox == 1 else 0 for i, ox in enumerate(oxygen[0])])
co2_dec = np.sum([2**(11-i) if co == 1 else 0 for i, co in enumerate(co2[0])])

print("Part 2:", oxygen_dec*co2_dec)

DAY 3 : Binary Diagnostic
Part 1: 738234
Part 2: 3969126


In [4]:
print("DAY 4 : Giant Squid")
draws = np.genfromtxt("inputs_2021/4.1.txt", delimiter=",")
boards = []
next_board = []
for line in open("inputs_2021/4.2.txt"):
    if line != "\n":
        next_board.append(np.fromstring(line, dtype=int, sep=" "))
        if len(next_board) == 5:
            boards.append(np.array(next_board))
            next_board = []
#boards = np.array(boards)

victory = 0
draw = 0
res=0
res2=0
blacklist = []
while victory < 100:
    for cnt,board in enumerate(boards):
        if cnt not in blacklist:
            for i in range(5):
                for j in range(5):
                    if board[i][j] == draws[draw]:
                        board[i][j] = -1
            for i in range(5):
                if np.sum(board[i]) == -5 or np.sum(board[:,i]) == -5:
                    if cnt not in blacklist:
                        if victory==0:
                            res = np.sum([np.sum([nb for nb in board[j] if nb !=-1]) for j in range(5)])
                            res *= draws[draw]
                        victory+=1
                        if victory == 100:
                            res2 = np.sum([np.sum([nb for nb in board[j] if nb !=-1]) for j in range(5)])
                            res2 *= draws[draw]
                        blacklist.append(cnt)

                    
    draw+=1

print("Part 1:", int(res))
print("Part 2:", int(res2))

DAY 4 : Giant Squid
Part 1: 45031
Part 2: 2568


In [5]:
print("DAY 5 : Hydrothermal Venture")
vents = []
for line in open("inputs_2021/5.txt"):
    vents.append((np.fromstring(line.split("-")[0], sep=","), np.fromstring((line.split(">")[1].split("\n")[0]), sep=",")))
vents=np.array(vents, dtype=int)

max_x = np.max([np.max((vent[0][0], vent[1][0])) for vent in vents])
max_y = np.max([np.max((vent[0][1], vent[1][1])) for vent in vents])
mp = np.zeros((max_x+1, max_y+1))

for vent in vents:
    #same X
    x1, x2 = vent[0][0], vent[1][0]
    y1, y2 = vent[0][1], vent[1][1]
    if x1 == x2:
        if y1 < y2:
            mp[x1][y1:y2+1] += 1
        else:
            mp[x1][y2:y1+1] += 1
    #same Y
    elif y1 == y2:
        if x1 < x2:
            mp[:,y1][x1:x2+1] += 1
        else:
            mp[:,y1][x2:x1+1] += 1

res = 0
for line in mp:
    for point in line:
        if point > 1:
            res+=1
print("Part 1: ", res)

mp = np.zeros((max_x+1, max_y+1))

for vent in vents:
    #same X
    x1, x2 = vent[0][0], vent[1][0]
    y1, y2 = vent[0][1], vent[1][1]
    if x1 == x2:
        if y1 < y2:
            mp[x1][y1:y2+1] += 1
        else:
            mp[x1][y2:y1+1] += 1
    #same Y
    elif y1 == y2:
        if x1 < x2:
            mp[:,y1][x1:x2+1] += 1
        else:
            mp[:,y1][x2:x1+1] += 1
    #diagonal
    else:
        if x2 > x1:
            if y2 > y1:
                for i in range(y2-y1+1):
                    mp[x1+i][y1+i] +=1
            else:
                for i in range(y1-y2+1):
                    mp[x1+i][y1-i] +=1
        else:
            if y2 > y1:
                for i in range(y2-y1+1):
                    mp[x1-i][y1+i] +=1
            else:
                for i in range(y1-y2+1):
                    mp[x1-i][y1-i]+=1
res = 0
for line in mp:
    for point in line:
        if point > 1:
            res+=1
            
print("Part 2:", res)

DAY 5 : Hydrothermal Venture
Part 1:  6113
Part 2: 20373


In [7]:
print("DAY 6 : Lanternfish")
lanternfishes = np.genfromtxt("inputs_2021/6.txt", delimiter=",")

nb_days = 80

#lanternfishes = np.array((3,4,3,1,2))
nb_days=18

for day in range(nb_days):
    for i in range(len(lanternfishes)):
        if lanternfishes[i] == 0:
            lanternfishes[i] = 6
            lanternfishes = np.append(lanternfishes,8)
        else:
            lanternfishes[i] -= 1
print("Part 1: ", len(lanternfishes))

DAY 6 : Lanternfish
Part 1:  1499


In [8]:
lanternfishes = np.genfromtxt("inputs_2021/6.txt", delimiter=",", dtype=int)
l_fishes = {}
for i in range(9):
    l_fishes[str(i)] = 0
for fish in lanternfishes:
    l_fishes[str(fish)]+=1

nb_days = 256

#lanternfishes = np.array((3,4,3,1,2))
#nb_days=18

for day in range(nb_days):
    to_birth = l_fishes["0"]
    for i in range(1, 9):
        l_fishes[str(int(i-1))] = l_fishes[str(i)]
    l_fishes["6"] += to_birth
    l_fishes["8"] = to_birth
    
    
print("Part 2: ", np.sum(list(l_fishes.values())))

Part 2:  1569108373832


In [9]:
print("DAY 7 : The Treachury of Whales")
crabs = np.genfromtxt("inputs_2021/7.txt", delimiter=",", dtype=int)

def get_fuel(pos):
    return np.sum([abs(crab - pos) for crab in crabs])

def get_fuel_part2(pos):
    return int(np.sum([abs(crab-pos)*((abs(crab-pos)+1)/2) for crab in crabs]))

min_fuel, min_fuel2 = float("inf"), float("inf")

for pos in range(crabs.min(), crabs.max()+1):
    
    score = get_fuel(pos)
    if score < min_fuel:
        min_fuel = score
    
    score2 = get_fuel_part2(pos) 
    if score2 < min_fuel2:
        min_fuel2=score2

print("Part 1: ",min_fuel)
print("Part 2: ",min_fuel2)

DAY 7 : The Treachury of Whales
Part 1:  353800
Part 2:  98119739


In [10]:
print("DAY 8 : Seven Segment Search")
inputs = []
outputs = []
for line in open("inputs_2021/8.txt"):
    inputs.append([inp.split("\n")[0] for inp in line.split("|")[0].split(" ")[:-1]])
    outputs.append([output.split("\n")[0] for output in line.split("|")[1].split(" ")[1:]])
    
unique_segments = [2, 3, 4, 7]

res=0
for output in outputs:
    for digit in output:
        if len(digit) in unique_segments:
            res+=1
print("Part 1: ", res)


res = 0
for entry in range(len(outputs)):
    digit1 = [digit for digit in inputs[entry] if len(digit) ==2][0]
    digit4 = [digit for digit in inputs[entry] if len(digit) ==4][0]
    digit8 = [digit for digit in inputs[entry] if len(digit) ==7][0]
    
    #LEN IS 6
    digits_len6 = [digit for digit in inputs[entry] if len(digit) == 6]
    digit6 = [digit for digit in digits_len6 if not (digit1[0] in digit and digit1[1] in digit)][0]
    digit8or9 = [digit for digit in digits_len6 if (digit1[0] in digit and digit1[1] in digit)]
    top = [letter for letter in [digit for digit in inputs[entry] if len(digit) ==3][0] if letter not in digit1][0]

    for digit in digit8or9:
        for letter in digit4:
            if letter not in digit:
                middle = letter
                digit9 = digit
    for letter in digit4:
        if letter not in middle+digit1:
            left_top = letter
    for letter in digit8:
        if letter not in digit9:
            left_bottom = letter
    for letter in digit9:
        if letter not in digit4+top+left_bottom:
            bottom = letter
    right_bottom = [letter for letter in digit1 if letter in digit6][0]
    right_top = [letter for letter in digit1 if letter not in digit6][0]
    
    full_digit = 0
    for i,digit in enumerate(outputs[entry]):
        if len(digit) == 2:
            val = 1
        elif len(digit) == 4:
            val = 4
        elif len(digit) == 3:
            val = 7
        elif len(digit) == 7:
            val = 8
        elif len(digit) == 5:
            if right_top in digit:
                if right_bottom in digit:
                    val = 3
                else:
                    val = 2
            else:
                val = 5
        elif len(digit) == 6:
            if middle not in digit:
                val = 0
            elif right_top not in digit:
                val = 6
            else:
                val = 9
        full_digit += val*10**(3-i)
        
    res += full_digit
print("Part 2: ", res)

DAY 8 : Seven Segment Search
Part 1:  530
Part 2:  1051087


In [11]:
print("DAY 9 : Smoke Basin")
heightmap = []
for line in open("inputs_2021/9.txt"):
    row=[]
    for val in line:
        if val != "\n":
            row.append(int(val))
    heightmap.append(row)
heightmap = np.array(heightmap)

def basin_size(i, j, blacklist=[]):
    #left
    #blacklist = np.array(blacklist)
    score = 0
    if (i,j) in blacklist:
        return 0, blacklist
    else:
        blacklist.append((i,j))
    if i-1 >= 0:
        if heightmap[i-1][j] > heightmap[i][j] and heightmap[i-1][j] != 9:
            size, blacklist = basin_size(i-1, j, blacklist)
            score += size
    if i+1 < mapx:
        if heightmap[i+1][j] > heightmap[i][j] and heightmap[i+1][j] != 9:
            size, blacklist = basin_size(i+1, j, blacklist)
            score += size
    if j-1 >= 0:
        if heightmap[i][j-1] > heightmap[i][j] and heightmap[i][j-1] != 9:
            size, blacklist = basin_size(i, j-1, blacklist)
            score += size
    if j+1 < mapy:
        if heightmap[i][j+1] > heightmap[i][j] and heightmap[i][j+1] != 9:
            size, blacklist = basin_size(i, j+1, blacklist)
            score += size
    np.append(blacklist, [i,j])
    return 1+score, blacklist
   
test = np.array([[2,1,9,9,9,4,3,2,1,0],
                [3,9,8,7,8,9,4,9,2,1],
                [9,8,5,6,7,8,9,8,9,2],
                [8,7,6,7,8,9,6,7,8,9],
                [9,8,9,9,9,6,5,6,7,8]])


mapx = len(heightmap)
mapy = len(heightmap[0])
res = 0 
basins = []
for i in range(mapx):
    for j in range(mapy):
        is_low = True
        #left
        if i-1 >= 0:
            if heightmap[i][j] >= heightmap[i-1][j]:
                is_low = False
        #right
        if i+1 < mapx:
            if heightmap[i][j] >= heightmap[i+1][j]:
                is_low = False
        #bottom
        if j-1 >= 0:
            if heightmap[i][j] >= heightmap[i][j-1]:
                is_low = False
        #up
        if j+1 < mapy:
            if heightmap[i][j] >= heightmap[i][j+1]:
                is_low = False
        if is_low:
            res += 1+heightmap[i][j]
            size, blacklist = basin_size(i,j)
            basins.append(size)
print("Part 1: ", res)


top3 = np.sort(basins)[-3:]
print("Part 2: ", top3.prod())

DAY 9 : Smoke Basin
Part 1:  475
Part 2:  1092012


In [13]:
print("DAY 10 : Syntax Scoring")
lines = []
for line in open("inputs_2021/10.txt"):
    lines.append(line.split("\n")[0])

res = 0
incomplete = []
for line in lines:
    next_close = []
    alive=True
    for c in line:
        if alive:
            if c in ['(', '[', '{', '<']:
                next_close.append(c)
            else:    
                if c == '}':
                    if next_close[-1] == '{':
                        next_close.pop()
                    else:
                        res += 1197
                        alive=False
                if c == ')':
                    if next_close[-1] == '(':
                        next_close.pop()
                    else:
                        res+=3
                        alive=False
                if c == ']':
                    if next_close[-1] == '[':
                        next_close.pop()
                    else:
                        res+=57
                        alive=False
                if c =='>':
                    if next_close[-1] == '<':
                        next_close.pop()
                    else:
                        res+=25137
                        alive=False
    if alive:
        score = 0
        for i in range(len(next_close)):
            score*=5
            c = next_close[-i-1]
            if c == '(':
                score+=1
            if c == '[':
                score+=2
            if c== '{':
                score+=3
            if c == '<':
                score+=4
        incomplete.append(score)
print("Part 1: ", res)
print("Part 2: ", int(np.median(incomplete)))

DAY 10 : Syntax Scoring
Part 1:  315693
Part 2:  1870887234


In [14]:
print("DAY 11 : Dumbo Octopus")
octo = []
for line in open("inputs_2021/11.txt"):
    octo.append([int(c) for c in line if c != "\n"])
octo=np.array(octo)
#print(octo)

size = len(octo)

def flash(octo):
    total_flashes=0
    for i in range(size):
        for j in range(size):
            if octo[i][j] > 9:
                octo[i][j] = -1
                total_flashes+= 1
                for x in range(-1,2):
                    for y in range(-1,2):
                        if not (x==0 and y==0) and i+x in range(size) and j+y in range(size):
                            if octo[i+x][j+y] != -1:
                                octo[i+x][j+y] += 1
                                total_flashes += flash(octo)
                            
    return total_flashes

steps = 100

flashes = 0

for i in range(steps):
    #Normal charging
    octo+=1
    flashes += flash(octo)
    for i in range(size):
        for j in range(size):
            if octo[i][j] == -1:
                octo[i][j] = 0
print("Part 1: ",flashes)
   
octo = []
for line in open("inputs_2021/11.txt"):
    octo.append([int(c) for c in line if c != "\n"])
octo=np.array(octo)

full_flash=False
steps=0
while not full_flash:
    #Normal charging
    octo+=1
    flashes += flash(octo)
    for i in range(size):
        for j in range(size):
            if octo[i][j] == -1:
                octo[i][j] = 0
    
    if np.sum(octo)==0:
        full_flash=True

    steps+=1
print("Part 2: ", steps)

DAY 11 : Dumbo Octopus
Part 1:  1620
Part 2:  371


In [15]:
print("DAY 12 : Passage Pathing")
caves = {}
for line in open("inputs_2021/12.txt"):
    node1, node2 = line.split("\n")[0].split("-")
    if node1 not in caves:
        caves[node1] = [node2]
    elif node2 not in caves[node1]:
        caves[node1].append(node2)
    if node2 not in caves:
        caves[node2] = [node1]
    elif node1 not in caves[node2]:
        caves[node2].append(node1)

def count_path(node, blacklist=[]):
    total = 0
    if node == "end":
            return 1
        
    if node.islower():
        blacklist.append(node)
    
    for edge in [nd for nd in caves[node] if nd not in blacklist]:    
        total += count_path(edge, blacklist)
    
    if node.islower():
        blacklist.pop()
    return total

print("Part 1: ",count_path("start"))

#CAN BE OPTIMIZED
all_path = []
def count_path2(node, blacklist=[], bonus_used = False, currpath=[]):
    total = 0
    currpath.append(node)
    if node == "end":
        if str(currpath) not in all_path:
            all_path.append(str(currpath))
            currpath.pop()
            return 1
        currpath.pop()

        return 0
        
    if node.islower():
        if not bonus_used and node != "start":
            #print("using bonus for ", node)
            for edge in [nd for nd in caves[node] if nd not in blacklist]:
                total+= count_path2(edge, blacklist, True, currpath)
      
        blacklist.append(node)
    
    for edge in [nd for nd in caves[node] if nd not in blacklist]:    
        total += count_path2(edge, blacklist, bonus_used, currpath)
    currpath.pop()
    if node.islower():
        blacklist.pop()
    return total
print("Part 2:", count_path2('start'))

DAY 12 : Passage Pathing
Part 1:  3563
Part 2: 105453


In [18]:
print("DAY 13 : Transparent Origami")
X = []
Y = []
for line in open("inputs_2021/13.1.txt"):
    x, y = line.split("\n")[0].split(",")
    X.append(int(x))
    Y.append(int(y))
#MATCH DIMENSION SO THAT FIRST FOLD APPEARS AT THE MIDDLE
max_X = np.max(X)+3
max_Y = np.max(Y)+1
class Paper:
    def __init__(self, max_X, max_Y):
        self.max_X = max_X
        self.max_Y = max_Y
        self.paper = np.zeros((max_Y, max_X))
    
    def addPoint(self, x, y):
        self.paper[y,x] = 1

    def fold(self, axis, value):
        if axis == "x":
            self.max_X = value
            new_paper = Paper(self.max_X, self.max_Y)
            
            new_paper.paper+=self.paper[:,:value]+np.flip(self.paper[:,-value:], axis=1)
            self.paper = new_paper.paper
            
        if axis == "y":
            self.max_Y = value
            new_paper = Paper(self.max_X, self.max_Y)
            up_side = self.paper[:value]
            down_side = self.paper[-value:]
            new_paper.paper+=self.paper[:value]+np.flip(self.paper[-value:], axis=0)
            self.paper = new_paper.paper
    def count(self):
        return np.count_nonzero(self.paper)

paper = Paper(max_X, max_Y)
for i in range(len(X)):
    paper.addPoint(X[i], Y[i])


#paper.fold("y", 7)
#print(paper.paper)
#paper.fold("x", 5)
folds = []
for line in open("inputs_2021/13.2.txt"):
    folds.append(line.split("\n")[0].split("along")[1].split("="))
paper.fold(folds[0][0][-1], int(folds[0][1]))
print("Part 1: ",paper.count())

for fold in folds[1:]:
    paper.fold(fold[0][-1], int(fold[1]))

print("Part 2")
for i in range(8):
    print("LETTER ", i)
    print(paper.paper[:,i*5:(i+1)*5])

DAY 13 : Transparent Origami
Part 1:  695
Part 2
LETTER  0
[[ 0. 12.  8.  0.  0.]
 [13.  0.  0.  6.  0.]
 [ 4.  0.  0.  0.  0.]
 [ 9.  0. 34. 10.  0.]
 [10.  0.  0. 12.  0.]
 [ 0.  5. 23.  3.  0.]]
LETTER  1
[[ 0.  0.  1.  3.  0.]
 [ 0.  0.  0. 16.  0.]
 [ 0.  0.  0. 17.  0.]
 [ 0.  0.  0. 12.  0.]
 [ 4.  0.  0.  1.  0.]
 [ 0.  7. 16.  0.  0.]]
LETTER  2
[[ 9.  5.  5.  6.  0.]
 [ 0.  0.  0.  3.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 3.  0.  0.  0.  0.]
 [20. 10. 14. 23.  0.]]
LETTER  3
[[ 0. 15.  6.  0.  0.]
 [ 2.  0.  0.  6.  0.]
 [22.  0.  0.  0.  0.]
 [ 2.  0.  5.  6.  0.]
 [ 5.  0.  0. 12.  0.]
 [ 0.  3.  8. 14.  0.]]
LETTER  4
[[ 5.  0.  0.  0.  0.]
 [12.  0.  0.  0.  0.]
 [ 7.  0.  0.  0.  0.]
 [ 4.  0.  0.  0.  0.]
 [20.  0.  0.  0.  0.]
 [32.  2.  8. 10.  0.]]
LETTER  5
[[ 2.  0.  0.  5.  0.]
 [ 4.  0.  0. 37.  0.]
 [ 5.  0.  0.  5.  0.]
 [ 8.  0.  0. 11.  0.]
 [ 2.  0.  0. 14.  0.]
 [ 0.  7.  9.  0.  0.]]
LETTER  6
[[ 7.  8. 21.  0.  0.]
 [22.  0.  0.  2.  0.]
 

In [19]:
print("DAY 14 : Extended Polymerization")
from collections import Counter

polymer = "COPBCNPOBKCCFFBSVHKO"
#polymer = "NNCB"
rules = {}
for line in open("inputs_2021/14.txt"):
    comb, insert = line.split("\n")[0].split("->")
    rules[comb.split(" ")[0]] = insert.split(" ")[1]


def run_steps(polymer, steps):
    for i in range(steps):
        #print("steps", i)
        new_polymer = ""
        new_polymer += polymer[0]
        for comb in range(len(polymer)-1):
            duo = polymer[comb]+polymer[comb+1]
            if duo in rules:
                new_polymer+= rules[duo]+duo[1]
            else:
                new_polymer+= duo[1]
        polymer = new_polymer

    counter = Counter(polymer)
    #print(counter)
    freq = list(counter.values())
    most_frequent = np.max(freq)
    least_frequent = np.min(freq)
    #print(polymer)
    return most_frequent - least_frequent
print("Part 1: ", run_steps(polymer, 10))


def run_steps_smart(polymer, steps):
    all_duos = {}
    for comb in range(len(polymer)-1):
        duo = polymer[comb]+polymer[comb+1]
        if duo not in all_duos:
            all_duos[duo] = 1
        else:
            all_duos[duo] += 1
    for i in range(steps):
        generation = {}
        for duo in all_duos:
            if duo in rules:
                amount = all_duos[duo]
                newduos = duo[0]+rules[duo], rules[duo]+duo[1]
                for newduo in newduos:
                    if newduo in generation:
                        generation[newduo]+=amount
                    else:
                        generation[newduo]=amount
                if duo in generation:   
                    generation[duo]-=amount
                else:
                    generation[duo] = -amount
        for key in generation:
            if key not in all_duos:
                all_duos[key] = generation[key]
            else:
                all_duos[key]+=generation[key]
    return all_duos

polymer = "COPBCNPOBKCCFFBSVHKO"
#polymer = "NNCB"                
all_duos = run_steps_smart(polymer, 40)

#Smart counter based on duos only
letter_counter = {}
for duo in all_duos:
    for letter in duo:    
        if letter not in letter_counter:
            letter_counter[letter] = all_duos[duo]
        else:
            letter_counter[letter] += all_duos[duo]
for letter in letter_counter:
    letter_counter[letter] = int(np.ceil(letter_counter[letter]/2))

print("Part 2: ", np.max(list(letter_counter.values()))- np.min(list(letter_counter.values())))

DAY 14 : Extended Polymerization
Part 1:  2602
Part 2:  2942885922173


In [65]:
from collections import defaultdict
import heapq as heap
import numpy as np
import collections

class Graph:
    def __init__(self):
        self.g = {}
        
    def add_edge(self, u, v, weight):
        #print("adding "+str(v)+" as neighbor of "+str(u)+" with dist "+str(weight))
        if str(u) not in self.g:
            self.g[str(u)] = {}
        self.g[str(u)][str(v)] = int(weight)

    def dijkstra(self, startingNode):
        visited = set()
        parentsMap = {}
        pq = []
        nodeCosts = defaultdict(lambda: float('inf'))
        nodeCosts[startingNode] = 0
        heap.heappush(pq, (0, startingNode))

        while pq:
            # go greedily by always extending the shorter cost nodes first
            _, node = heap.heappop(pq)
            visited.add(node)

            for adjNode, weight in self.g[node].items():
                if adjNode in visited:   continue

                newCost = nodeCosts[node] + weight
                if nodeCosts[adjNode] > newCost:
                    parentsMap[adjNode] = node
                    nodeCosts[adjNode] = newCost
                    heap.heappush(pq, (newCost, adjNode))
        
        return parentsMap, nodeCosts

In [20]:
from collections import defaultdict
import heapq as heap
import numpy as np
import collections

print("DAY 15 : Chiton")

class Graph:
    def __init__(self):
        self.g = {}
        
    def add_edge(self, u, v, weight):
        #print("adding "+str(v)+" as neighbor of "+str(u)+" with dist "+str(weight))
        if str(u) not in self.g:
            self.g[str(u)] = {}
        self.g[str(u)][str(v)] = int(weight)

    def dijkstra(self, startingNode):
        visited = set()
        parentsMap = {}
        pq = []
        nodeCosts = defaultdict(lambda: float('inf'))
        nodeCosts[startingNode] = 0
        heap.heappush(pq, (0, startingNode))

        while pq:
            # go greedily by always extending the shorter cost nodes first
            _, node = heap.heappop(pq)
            visited.add(node)

            for adjNode, weight in self.g[node].items():
                if adjNode in visited:   continue

                newCost = nodeCosts[node] + weight
                if nodeCosts[adjNode] > newCost:
                    parentsMap[adjNode] = node
                    nodeCosts[adjNode] = newCost
                    heap.heappush(pq, (newCost, adjNode))
        
        return parentsMap, nodeCosts

cave = []
for line in open("inputs_2021/15.txt"):
    row =[]
    for val in line.split("\n")[0]:
        row.append(int(val))
    cave.append(row)
#cave = cave[:50][:50]
dim = len(cave)
cave = np.array(cave)
#print(cave)
g1 = Graph()
for i in range(dim):
    for j in range(dim):
        if j+1 < dim:
            g1.add_edge(i*dim+j,i*dim+j+1, cave[i,j+1])
        if i+1 < dim:
            g1.add_edge(i*dim+j, (i+1)*dim+j, cave[i+1,j])
        if j-1 >= 0:
            g1.add_edge(i*dim+j, i*dim+j-1, cave[i,j-1])
        if i-1 >= 0:
            g1.add_edge( i*dim+j,(i-1)*dim+j, cave[i-1,j])
res = g1.dijkstra("0")
print("Part 1: ", res[1][str(dim*dim-1)])

DAY 15 : Chiton
Part 1:  621


In [21]:
dim = len(cave)
augmented_cave = np.zeros((5*dim, 5*dim))
for i in range(dim):
    for j in range(dim):
        for z in range(0,5):
            for w in range(0,5):
                if z == 0 and w == 0:
                    augmented_cave[i,j] = cave[i,j]
                else:
                    if cave[i,j]+w+z > 9:
                        augmented_cave[dim*w+i,dim*z+j] = cave[i,j]+w+z - 9
                    else:
                        augmented_cave[i+dim*w,dim*z+j] = cave[i,j] + w+z
new_dim = 5*dim

g2 = Graph()

for i in range(new_dim):
    for j in range(new_dim):
        if j+1 < new_dim:
            g2.add_edge(i*new_dim+j,i*new_dim+j+1, augmented_cave[i,j+1])
        if i+1 < new_dim:
            g2.add_edge(i*new_dim+j, (i+1)*new_dim+j, augmented_cave[i+1,j])
        if j-1 >= 0:
            g2.add_edge(i*new_dim+j, i*new_dim+j-1, augmented_cave[i,j-1])
        if i-1 >= 0:
            g2.add_edge( i*new_dim+j,(i-1)*new_dim+j, augmented_cave[i-1,j])
res = g2.dijkstra("0")
print("Part 2: ", res[1][str(new_dim*new_dim-1)])

Part 2:  2904


In [22]:
print("DAY 16 : Packet Decoder")
for line in open("inputs_2021/16.txt"):
    #line = "9C0141080250320F1802104A08"
    number, pad, rjust, size, kind = int(line, 16), '0', '>', int(len(line)*4), 'b'
    transmission = f'{number:{pad}{rjust}{size}{kind}}'

#print(transmission)
def read_packet(packet):
    version = int(packet[:3], 2)
    type_id = int(packet[3:6], 2)
    #print("version ",version)
    #print("id ", type_id)
    if type_id == 4:
        #print("litteral value")
        content = packet[6:]
        i = 0
        value = ""
        while True:
            value += content[i*5+1:i*5+5]
            if content[i*5] == "0":
                break
            i+=1
        return {"version":version, "type_id":type_id, "content":int(value, 2), "packet_len":6+i*5+5}
    else:
        subpackets = []
        sum_version_id = 0
        length_id = packet[6]
        total_len = 0
        #print("length id ", length_id)
        if length_id == "0":
            content_len = int(packet[7:22], 2)
            #print("content len ", content_len)
            while total_len < content_len:
                #print("total len", total_len)
                nextpacket = read_packet(packet[22+total_len:])
                total_len += nextpacket["packet_len"]
                sum_version_id += nextpacket["version"]
                subpackets.append(nextpacket)
                packet_len = 6+1+15+content_len
        elif length_id == "1":
            subpackets_amount = int(packet[7:18], 2)
            #print("subpackets amount :", subpackets_amount)
            while len(subpackets) < subpackets_amount:
                nextpacket = read_packet(packet[18+total_len:])
                total_len += nextpacket["packet_len"]
                sum_version_id += nextpacket["version"]
                subpackets.append(nextpacket)
                packet_len = 6+1+11+total_len
        subpackets_contents = np.array([subpacket["content"] for subpacket in subpackets], dtype=float)
        if type_id == 0:
            content = np.sum(subpackets_contents)
        elif type_id == 1:
            content = np.prod(subpackets_contents)
        elif type_id == 2:
            content = np.min(subpackets_contents)
        elif type_id == 3:
            content = np.max(subpackets_contents)
        elif type_id == 5:
            content = 0
            if subpackets_contents[0] > subpackets_contents[1] :
                content = 1
        elif type_id == 6:
            content = 0
            if subpackets_contents[0] < subpackets_contents[1] :
                content = 1
        elif type_id == 7:
            content = 0
            if subpackets_contents[0] == subpackets_contents[1]:
                content = 1
        return {"version":version+sum_version_id, "type_id":type_id, 
                    "content":int(content), "packet_len":packet_len}
read_packet(transmission)

DAY 16 : Packet Decoder


{'version': 1007, 'type_id': 0, 'content': 834151779165, 'packet_len': 5460}

In [23]:
print("DAY 17 : Trick Shot")
#target area: x=119..176, y=-141..-84
targetX = np.arange(119,177)
targetY = np.arange(-141, -83)
#targetX = np.arange(20,31)
#targetY = np.arange(-10, -4)

def simulate_launch(x, y):
    pos = [0,0]
    maxY = 0
    while pos[0] < targetX[-1] and pos[1] > targetY[0]:
        pos[0] += x
        pos[1] += y
        if pos[1] > maxY:
            maxY = pos[1]
        if x > 0:
            x -= 1
        y -= 1
        if pos[0] in targetX and pos[1] in targetY:
            return True, maxY
    return False, maxY

#Quick math
n = -(targetY[0]+1)
print("Part 1: ", int(n*(n+1)/2))

total = 0
for i in range(178):
    for j in range(-141, 141):
        res = simulate_launch(i,j)
        if res[0] == True:
            total+=1
    
print("Part 2: ",total)

DAY 17 : Trick Shot
Part 1:  9870
Part 2:  5523


In [24]:
from binarytree import Node

print("DAY 18 : Snailfish")
additions = []
for line in open("inputs_2021/18.txt"):
    additions.append(line.split("\n")[0])

class Nodess:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None
    
foo = "[[[0,[4,5]],[0,0]],[[[4,5],[2,6]],[9,5]]]"
faa = "[7,[[[3,7],[4,3]],[[6,3],[8,8]]]]"
#foo = "[[[[3,0],[5,3]],[4,4]],[5,5]]"
#faa = "[6,6]"
def snail2tree(snail, node =Node("pair")):
    c = snail[0]
    if c == "[":
        node = Node("pair")
        snail, node.left = snail2tree(snail[1:], node)
        snail, node.right = snail2tree(snail, node)
        return snail, node
    if c.isnumeric():
        return snail[1:], Node(int(c))
    if c == ",":
        snail, next_node = snail2tree(snail[1:])
        return snail, next_node
    return snail2tree(snail[1:])
#snail, tree = snail2tree(additions[0])
#print('Binary tree :\n', tree)
s, foo_tree = snail2tree(foo)
s, faa_tree = snail2tree(faa)
#print(foo_tree)
#print(faa_tree)

def snail_sum(tree1, tree2):
    node = Node("pair")
    node.left = tree1
    node.right = tree2
    return node


fee_tree = snail_sum(foo_tree, faa_tree)
#print(fee_tree)

#s, fee_tree = snail2tree(fee)
#print(fee_tree)

def update_explosion_right(n, value):
    #print("expl", n)
    if n.value != "pair":
        n.value += value
        return True
    if n.left is not None:
        if n.left.value != "pair":
            n.left.value += value
            return True
        else:
            if not update_explosion_right(n.left, value):
                if n.right is not None:
                    if n.right.value != "pair":
                        n.right.value += value
                        return True
                    else:
                        return update_explosion_right(n.right, value)
            else:
                return True
            
    return False
def snail_reduce(node, deepness = 0, visited = []):
    if deepness == 4 and node.value == "pair":
        #print("explode")
        foundLeft = False
        foundRight = False
        left_value = node.left.value
        right_value = node.right.value
        #going left
        
        for n in reversed(visited):
                
            if n.value != "pair" and not foundLeft:
                n.value += left_value
                foundLeft = True
            if n!= node and n.right!= node and not foundRight and n.right is not None and n.right not in visited:
                #print("found condition ",n)
                if n.right.value != "pair":
                    n.right.value += right_value
                    foundRight = True
                else:
                    foundRight = update_explosion_right(n.right, right_value)
            
         
        
        node.value = 0
        node.left = None
        node.right = None
    
        return True
    else:
        visited.append(node)
        if node.value == "pair":
            deepness+=1
        if node.left is not None:  
            if snail_reduce(node.left, deepness, visited):
                return True
            elif node.right is not None:
                return snail_reduce(node.right, deepness, visited)
    #Handle split
    
    return False
def handle_split(node):
    if node.left is not None:
        if not handle_split(node.left) and node.right is not None:
            return handle_split(node.right)
        else:
            return True
    if node.value != "pair":
        if node.value >= 10:
            #print("split")
            left_val = int(node.value/2)
            right_val = int((node.value+1)/2)
            node.value = "pair"
            node.left = Node(left_val)
            node.right = Node(right_val)
            return True
    return False

def magnitude(node):
    if node.value != "pair":
        return node.value
    else:
        return 3*magnitude(node.left) + 2*magnitude(node.right)
aadditions = [
"[[[0,[5,8]],[[1,7],[9,6]]],[[4,[1,2]],[[1,4],2]]]",
"[[[5,[2,8]],4],[5,[[9,9],0]]]",
"[6,[[[6,2],[5,6]],[[7,6],[4,7]]]]",
"[[[6,[0,7]],[0,9]],[4,[9,[9,0]]]]",
"[[[7,[6,4]],[3,[1,3]]],[[[5,5],1],9]]",
"[[6,[[7,3],[3,2]]],[[[3,8],[5,7]],4]]",
"[[[[5,4],[7,7]],8],[[8,3],8]]",
"[[9,3],[[9,9],[6,[4,9]]]]",
"[[2,[[7,7],7]],[[5,8],[[9,3],[0,2]]]]",
"[[[[5,2],5],[8,[3,7]]],[[5,[7,5]],[4,4]]]",
]

#additions = ["[[[[4,0],[5,4]],[[7,7],[6,0]]],[[8,[7,7]],[[7,9],[5,0]]]]", "[[2,[[0,8],[3,4]]],[[[6,7],1],[7,[1,6]]]]"]
s, res_tree = snail2tree(additions[0])
for addition in additions[1:]:
    #print(addition)
    #print("left side : ", res_tree)
    s, add_tree = snail2tree(addition)
    #print("right side : ", add_tree)
    res_tree = snail_sum(res_tree, add_tree)
    #print("addition : ", res_tree)
    while True:
        if not snail_reduce(res_tree, visited = []):
            if not handle_split(res_tree):
                break
print(res_tree)
    #print("after reduction", res_tree)    
print("Part 1: ", magnitude(res_tree))



DAY 18 : Snailfish

                          _________________________pair________________________
                         /                                                     \
            ___________pair__________                               ___________pair__________
           /                         \                             /                         \
     ____pair___                 ____pair___                 ____pair___                 ____pair___
    /           \               /           \               /           \               /           \
  pair          pair          pair          pair          pair          pair          pair          pair
 /    \        /    \        /    \        /    \        /    \        /    \        /    \        /    \
7      6      6      7      7      7      7      8      8      0      8      7      6      8      6      0

Part 1:  3981


In [25]:
max_magnitude = 0
for source in additions:
    #print(source)
    
    for addition in [add for add in additions if add != source]:
        s, source_tree = snail2tree(source)
        #print(addition)
        #print("left side : ", res_tree)
        s, add_tree = snail2tree(addition)
        #print("right side : ", add_tree)
        res_tree = snail_sum(source_tree, add_tree)
        #print("addition : ", res_tree)
        while True:
            if not snail_reduce(res_tree, visited = []):
                if not handle_split(res_tree):
                    break
        
        magn = magnitude(res_tree)
        if magn > max_magnitude:
            max_magnitude = magn
print("Part 2 : ",max_magnitude)


Part 2 :  4687


In [98]:
import itertools
import numpy as np

print("DAY 19 : BEACON SCANNER")
scanners = []
for line in open("inputs_2021/19.txt"):
    if len(line) > 2:
        if line[1] == "-":
            scanner = []
        else:
            scanner.append(np.array([int(val) for val in line.split("\n")[0].split(",")]))
    else:
        scanners.append(np.array(scanner))
scanners.append(np.array(scanner))

def centeroid(arr):
    length, dim = arr.shape
    return np.array([np.sum(arr[:, i])/length for i in range(dim)])

#print(scanner1)
#print(scanners)
def change_referential(p1, points): 
    res = []
    for p in points:
        res.append(p-p1)
    return np.array(res)

def check_overlap(ref1, ref2):
    res = []
    for p in ref1:
        if (p != np.zeros(3)).all():
            for p2 in ref2:
                if abs(p[0]) in abs(p2) and abs(p[1]) in abs(p2) and abs(p[2]) in abs(p2):                    
                    res.append((p, p2))
    #print(res[0])
    return np.array(res)

def overlap(scan1, scan2):
    for beacon1 in scan1:
        ref_points1 = change_referential(beacon1, scan1)

        for beacon2 in scan2:
            ref_points2 = change_referential(beacon2, scan2)
            overlaps = check_overlap(ref_points1, ref_points2)
            if len(overlaps) >= 11:
                point_overlap1 = overlaps[0][0]
                point_overlap2 = overlaps[0][1]
                #print(point_overlap1)
                #print(point_overlap2)
                transf = np.zeros((3,3))
                for i in range(3):
                    for j in range(3):
                        if point_overlap1[i] == point_overlap2[j]:
                            transf[j][i] = 1
                        elif point_overlap1[i] == -point_overlap2[j]:
                            transf[j][i] = -1
                #print(transf)
                p1 = beacon1+overlaps[0][0]
                p2 = np.dot(beacon2+overlaps[0][1], transf)
                #print("all_points from 1 : ", change_referential(-beacon1, overlaps[:,0]))
                #print("all_points from 2 : ", change_referential(-beacon2, overlaps[:,1]))
                print("p1", p1)
                print("p2", beacon2+overlaps[0][1])
                #print(overlaps[0])
                #print(overlaps[0][0][0] + overlaps[0][1][0])
                return p1 - p2, transf
    return None

#print(len(check_overlap(new_ref1, new_ref2)))
#scan1fromscan0, transf = overlap(scanners[0], scanners[1])
#print(scan1fromscan0)
#print(change_referential(-scan1fromscan0, scanners[1].dot(transf)))
#scan4fromscan0 = np.array([-20,-1133,1061])
#scan4fromscan1 = scan4fromscan0 - scan1fromscan0
#print("OBJECTIVE", scan4fromscan1)
#scan4fromscan1, transf2 = overlap(scanners[1], scanners[4])
#print(scan4fromscan1.dot(transf)+scan1fromscan0)
#print("POINTS OF SCAN 1 SEEN BY SCAN 1 : ", scanners[1])
#print("POINTS OF SCAN 4 SEEN BY SCAN 1", scan4fromscan1 + scanners[4].dot(transf2))
#print(change_referential(-scan1fromscan0, change_referential(-scan4fromscan1, scanners[4].dot(transf2)).dot(transf)))

remaining_scanners = scanners[1:]
source = scanners[0]
link_scanners = [source]
beacons = [b for b in scanners[0]]
all_scanners = [(0,0,0)]
j=0
while len(remaining_scanners) > 0:
    for i, scan in enumerate(remaining_scanners):
        #print("scanner ",scan)
        #print("potential pair : ", link_scanners[i])
        res = overlap(link_scanners[j], scan)
        if res is not None:
            #print("Found overlap")
            scanPos, scanOri = res
            all_scanners.append(scanPos)
            new_beacons = scanPos + scan.dot(scanOri)
            for new_b in new_beacons:
                collision=False
                for b in beacons:
                    if (b==new_b).all():
                        collision = True
                if not collision:
                    beacons.append(new_b)
            link_scanners.append(np.array(new_beacons, dtype=int))
            #print("link " ,link_scanner)
            #print("originated from : ", scan)
            remaining_scanners.pop(i)
            #print(len(beacons))
            #print("remaining scanners : ", len(remaining_scanners))
            break
    j = (1+j)%len(link_scanners)
print("Part 1 : ", len(beacons))


DAY 19 : BEACON SCANNER
p1 [-611 -859  516]
p2 [-629  656 -335]
40
remaining scanners :  36
p1 [ -508 -1653   515]
p2 [-521 -421  680]
54
remaining scanners :  35
p1 [-1590  -646   435]
p2 [-412  591 -487]
62
remaining scanners :  34
p1 [-1912  -469  -508]
p2 [765 689 513]
76
remaining scanners :  33
p1 [-280  628 -633]
p2 [-498 -381  692]
84
remaining scanners :  32
p1 [ -563  -400 -2067]
p2 [-338  626 -388]
98
remaining scanners :  31
p1 [  748   507 -3195]
p2 [-754 -790 -686]
112
remaining scanners :  30
p1 [  407  1898 -1970]
p2 [634 274 801]
120
remaining scanners :  29
p1 [  515   728 -1900]
p2 [-531  586  724]
134
remaining scanners :  28
p1 [ 806  695 -591]
p2 [ 547  569 -466]
145
remaining scanners :  27
p1 [2147  703 -802]
p2 [-232 -736  561]
159
remaining scanners :  26
p1 [807 441 685]
p2 [826 766 873]
164
remaining scanners :  25
p1 [-1943   377   530]
p2 [-523 -819  815]
172
remaining scanners :  24
p1 [ 806  695 -591]
p2 [ 451  593 -628]
180
remaining scanners :  23
p1 [

In [104]:
all_scanners = np.array(all_scanners)
max_dist = 0
for i in range(len(all_scanners)):
    for j in range(len(all_scanners)):
        if i != j:
            dist = np.sum(abs(all_scanners[i] - all_scanners[j]))
            #print(dist)
            max_dist = np.max((max_dist, dist))
print("Part 2 : ", int(max_dist))

Part 2 :  12140


In [27]:
print("DAY 20: TRENCH MAP")


image = []
img=False
for line in open("inputs_2021/20.txt"):
    if not img:
        if line == "\n":
            img = True
        else:
            algo = line.split("\n")[0]
    else:
        image.append(line.split("\n")[0])

image = np.array([[1 if c == "#" else 0 for c in row] for row in image])#[:5, :5]
steps = 50

for s in range(steps):
    #print(s)
    if s % 2 == 0:
        new_image = np.zeros((len(image)+8, len(image)+8))
    else: 
        new_image = np.ones((len(image)+8, len(image)+8))
    for i in range(len(image)):
        for j in range(len(image)):
            new_image[i+4][j+4] = image[i][j]
    image = new_image.copy()
    #print("before : ", image)
    for i in range(1, len(new_image)-1):
        for j in range(1, len(new_image)-1):
            key = np.concatenate(new_image[i-1:i+2, j-1:j+2])
            bin_key = ""
            for c in key:
                if c == 1:
                    bin_key+="1"
                else:
                    bin_key+="0"
            #print(bin_key)
            bin_key = int(bin_key, 2)
            val = algo[bin_key]
            if val == "#":
                image[i,j] = 1
            else:
                image[i,j] = 0
    image = image[1:-1, 1:-1]
    #print("after" , image)
padd = 6
#print("final image ", image[padd:-padd, padd:-padd])
print("Part X : ", np.count_nonzero(image))

DAY 20: TRENCH MAP
Part X :  15714


In [28]:
print("DAY 21 : Dirac Dice")

#Player 1 starting position: 4
#Player 2 starting position: 5

player1 = 4
player2 = 5
score1 = 0
score2 = 0
threshold = 1000
#r = 18
i = 1
boardsize = 10

while score1 < 1000 and score2 < 1000:
    player1 = ((((i*3-1)* 3) + player1) -1) % 10 + 1
    score1+=player1
    #print(score1)
    i+=1
    if score1 >= 1000:
        #print("score of player2" ,score2)
        #print("rolled ", i*3 - 3)
        print("Part 1 : ", score2*(i*3 - 3))
        break
    else:
        player2 = ((((i*3-1)* 3) + player2) -1) % 10 + 1
        score2+=player2
        i+=1
        if score2 >=1000:
            #print("score of player1", score1)
            #print("rolled", i*3 - 3)
            print("Part 1 : ", score1*(i*3 - 3))
            break

threshold = 21
scores1 = {}
scores2 = {}
player1 = {}
player2 = {}

#3, 9 : 1 way
#4, 8 : 3 ways
#5, 7 : 6 ways
#6 : 7 ways

dirac = {"3" : 1, "4" : 3, "5" : 6, "6" : 7, "7" : 6, "8" : 3,  "9" : 1}

for i in range(1, 11):
    player1[str(i)] = {}
    player2[str(i)] = {}
player1["4"]["0"] = 1
player2["5"]["0"] = 1

end_counter1 = {}
end_counter2 = {}
    
steps = 10
win_counter1 = 0
win_counter2 = 0
for step in range(steps):
    #print(step)
    new_player1 = {}
    new_player2 = {}
    for i in range(1, 11):
        new_player1[str(i)] = {}
        new_player2[str(i)] = {}
    for multiverse_sync in player1:
        for universe in dirac:
            new_index = (int(multiverse_sync) + int(universe) - 1)%10 + 1
            for score in player1[multiverse_sync]:
                new_score = new_index + int(score)
                if new_score >= threshold:
                    if str(step) not in end_counter1:
                        end_counter1[str(step)] = player1[multiverse_sync][score] * dirac[universe]
                    else:
                        end_counter1[str(step)] += player1[multiverse_sync][score] * dirac[universe]
                else:
                    if str(new_score) not in new_player1[str(new_index)]:
                        new_player1[str(new_index)][str(new_score)] = player1[multiverse_sync][score] * dirac[universe]
                    else:
                        new_player1[str(new_index)][str(new_score)] += player1[multiverse_sync][score] * dirac[universe]
    player1 = new_player1.copy()
    
    
    total_multiverses2 = 0

    for case in player2:
        total_multiverses2+=np.sum(list(player2[case].values()))
    if str(step) in end_counter1:
        win_counter1 += float(end_counter1[str(step)]) * total_multiverses2
        #print("step "+str(step)+ ", Player 1 : " + str(float(end_counter1[str(step)]) * total_multiverses2))
    
    for multiverse_sync in player2:
        for universe in dirac:
            new_index = (int(multiverse_sync) + int(universe) - 1)%10 + 1
            for score in player2[multiverse_sync]:
                new_score = new_index+int(score)
                if new_score >= threshold:
                    if str(step) not in end_counter2:
                        end_counter2[str(step)] = player2[multiverse_sync][score] * dirac[universe]
                    else:
                        end_counter2[str(step)] += player2[multiverse_sync][score] * dirac[universe]
                else:
                    if str(new_score) not in new_player2[str(new_index)]:
                        new_player2[str(new_index)][str(new_score)] = player2[multiverse_sync][score] * dirac[universe]
                    else:
                        new_player2[str(new_index)][str(new_score)] += player2[multiverse_sync][score] * dirac[universe]
    player2 = new_player2
    
    total_multiverses1 = 0

    for case in player1:
        total_multiverses1+=np.sum(list(player1[case].values()))
    
    if str(step) in end_counter2:
        win_counter2 += float(end_counter2[str(step)]) * total_multiverses1
        #print("step "+str(step)+ ", Player 2 : " + str(float(end_counter2[str(step)]) * total_multiverses1))
    

print("win counter 1 : ", int(win_counter1))
print("win counter 2 : ", int(win_counter2))

DAY 21 : Dirac Dice
Part 1 :  864900
win counter 1 :  575111835924670
win counter 2 :  392525387812463


In [17]:
import numpy as np
print("DAY 22 : Reactor Reboot")

reboot = []
for line in open("inputs_2021/22.1.txt"):
    trigger = line.split(" ")[0]
    xrange = np.array(line.split(",")[0].split("=")[1].split(".."), dtype = int)
    yrange = np.array(line.split(",")[1].split("=")[1].split("..") , dtype=int)
    zrange = np.array(line.split(",")[2].split("=")[1].split("\n")[0].split("..") , dtype=int)
    
    trig = 0
    if trigger == "on":
        trig = 1
    reboot.append([trig, xrange, yrange, zrange])

reactor = np.zeros((101,101,101))
offset = 50

for command in reboot:
    if command[1][0] <= 50 and command[1][0] >= -50:
        for x in range(command[1][0], command[1][1]+1):
            for y in range(command[2][0], command[2][1]+1):
                for z in range(command[3][0], command[3][1]+1):
                    #print("x", x)
                    #print("y", y)
                    #print("z", z)
                    reactor[x+offset][y+offset][z+offset] = command[0]
print("Part 1: ", np.count_nonzero(reactor))

reactor = []

for command in reboot:
    if command[0] == 1:
        #Add range
        intersection = False
        for cuboid in reactor:
            #Intersection first boundary 
            #X
            if command[1][0] >= cuboid[0][0] and command[1][0] <= cuboid[0][1]:
                #Y
                if command[2][0] >= cuboid[1][0] and command[2][0] <= cuboid[1][1]:
                    #Z
                    if command[3][0] >= cuboid[2][0] and command[3][0] <= cuboid[2][1]:
                        
                

DAY 22 : Reactor Reboot
Part 1:  474140
